// frontend/src/views/Pacientes.vue
<template>
  <div class="space-y-6">
    <!-- Stats -->
    <div class="flex items-center gap-2 text-sm text-slate-500">
      <UsersIcon class="h-4 w-4" />
      <span>{{ mockPacientes.length }} pacientes cadastrados</span>
    </div>

    <!-- Search -->
    <div class="relative max-w-md">
      <MagnifyingGlassIcon class="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" />
      <input
        v-model="searchQuery"
        type="text"
        placeholder="Buscar por nome ou CPF..."
        class="w-full pl-9 pr-4 py-2 text-sm border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-teal-500 focus:border-teal-500"
      />
    </div>

    <!-- LGPD CPF warning -->
    <div
      v-if="isCpfSearch && !isCpfComplete && searchQuery.length > 0"
      class="rounded-md border border-amber-200 bg-amber-50 px-4 py-2 text-sm text-amber-800"
    >
      Digite o CPF completo para buscar (LGPD)
    </div>

    <!-- Empty state -->
    <div v-if="filteredPacientes.length === 0" class="flex flex-col items-center justify-center py-16 text-center">
      <XMarkIcon class="h-10 w-10 text-slate-300 mb-3" />
      <p class="text-sm font-medium text-slate-600">
        {{ isCpfSearch && !isCpfComplete ? 'Digite o CPF completo' : 'Nenhum paciente encontrado' }}
      </p>
      <p class="text-xs text-slate-400 mt-1">
        {{ isCpfSearch && !isCpfComplete
          ? 'Por razões de privacidade (LGPD), a busca por CPF requer o número completo.'
          : 'Tente ajustar os termos de busca.' }}
      </p>
    </div>

    <!-- Table -->
    <template v-else>
      <div class="overflow-x-auto rounded-lg border border-slate-200 shadow-sm">
        <table class="min-w-full">
          <thead>
            <tr class="bg-slate-50 border-b border-slate-200">
              <th class="pl-5 pr-3 py-3 text-left text-xs font-medium text-slate-500 uppercase tracking-wide w-72">Paciente</th>
              <th class="px-3 py-3 text-left text-xs font-medium text-slate-500 uppercase tracking-wide hidden sm:table-cell w-24">Idade</th>
              <th class="px-3 py-3 text-left text-xs font-medium text-slate-500 uppercase tracking-wide hidden md:table-cell w-40">Prontuário</th>
              <th class="px-3 py-3 text-left text-xs font-medium text-slate-500 uppercase tracking-wide hidden lg:table-cell w-48">CPF</th>
              <th class="px-3 py-3 text-left text-xs font-medium text-slate-500 uppercase tracking-wide hidden xl:table-cell w-36">Última consulta</th>
            </tr>
          </thead>
          <tbody class="divide-y divide-slate-100">
            <tr
              v-for="paciente in paginatedPacientes"
              :key="paciente.id"
              class="cursor-pointer hover:bg-slate-50 h-14 transition-colors"
              @click="handleRowClick(paciente)"
            >
              <td class="pl-5 pr-3 py-3">
                <div class="flex items-center gap-3">
                  <div class="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-teal-100 text-teal-700 text-sm font-semibold">
                    {{ getInitials(paciente.nome) }}
                  </div>
                  <div class="min-w-0">
                    <p class="font-medium text-slate-900 truncate">{{ paciente.nome }}</p>
                    <div class="flex flex-wrap gap-2 sm:hidden mt-0.5 text-xs text-slate-500">
                      <span>{{ paciente.idade }}</span>
                      <span>{{ paciente.prontuario }}</span>
                    </div>
                  </div>
                </div>
              </td>
              <td class="px-3 py-3 text-sm text-slate-700 hidden sm:table-cell">{{ paciente.idade }}</td>
              <td class="px-3 py-3 text-sm text-slate-500 hidden md:table-cell">{{ paciente.prontuario }}</td>
              <td class="px-3 py-3 hidden lg:table-cell" @click.stop>
                <div class="flex items-center gap-2">
                  <span class="text-sm font-mono text-slate-500">
                    {{ revealedCpfs.has(paciente.id) ? paciente.cpf : maskCpf(paciente.cpf ?? '') }}
                  </span>
                  <button
                    class="p-1 rounded text-slate-400 hover:text-slate-600 hover:bg-slate-100"
                    @click="toggleCpfReveal(paciente.id)"
                  >
                    <EyeSlashIcon v-if="revealedCpfs.has(paciente.id)" class="h-3.5 w-3.5" />
                    <EyeIcon v-else class="h-3.5 w-3.5" />
                  </button>
                </div>
              </td>
              <td class="px-3 py-3 text-sm text-slate-500 hidden xl:table-cell">
                {{ getLastConsultation(paciente) }}
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <!-- Pagination -->
      <div v-if="filteredPacientes.length > PAGE_SIZE" class="flex items-center justify-between pt-2 border-t border-slate-200">
        <p class="text-sm text-slate-500">
          Mostrando {{ (currentPage - 1) * PAGE_SIZE + 1 }}–{{ Math.min(currentPage * PAGE_SIZE, filteredPacientes.length) }} de {{ filteredPacientes.length }} pacientes
        </p>
        <div class="flex items-center gap-2">
          <button
            :disabled="currentPage === 1"
            @click="currentPage--"
            class="inline-flex items-center gap-1 rounded-md border border-slate-200 px-3 py-1.5 text-sm text-slate-600 hover:bg-slate-50 disabled:opacity-40 disabled:cursor-not-allowed"
          >
            <ChevronLeftIcon class="h-4 w-4" />
            Anterior
          </button>
          <span class="text-sm font-medium px-2">{{ currentPage }} / {{ totalPages }}</span>
          <button
            :disabled="currentPage === totalPages"
            @click="currentPage++"
            class="inline-flex items-center gap-1 rounded-md border border-slate-200 px-3 py-1.5 text-sm text-slate-600 hover:bg-slate-50 disabled:opacity-40 disabled:cursor-not-allowed"
          >
            Próxima
            <ChevronRightIcon class="h-4 w-4" />
          </button>
        </div>
      </div>
    </template>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch } from 'vue'
import { useRouter } from 'vue-router'
import {
  UsersIcon,
  MagnifyingGlassIcon,
  XMarkIcon,
  EyeIcon,
  EyeSlashIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
} from '@heroicons/vue/24/outline'
import { mockPacientes } from '../stores/paciente'
import type { Paciente } from '../types/clinica'
import { maskCpf } from '../utils/cpf'

const router = useRouter()

const PAGE_SIZE = 20
const searchQuery = ref('')
const currentPage = ref(1)
const revealedCpfs = ref(new Set<string>())

const isCpfSearch = computed(() => /[\d.-]/.test(searchQuery.value))
const normalizedCpfQuery = computed(() => searchQuery.value.replace(/\D/g, ''))
const isCpfComplete = computed(() => normalizedCpfQuery.value.length === 11)

const filteredPacientes = computed<Paciente[]>(() => {
  if (!searchQuery.value.trim()) {
    return [...mockPacientes].sort((a, b) => a.nome.localeCompare(b.nome))
  }
  if (isCpfSearch.value) {
    if (!isCpfComplete.value) return []
    return mockPacientes.filter(p => (p.cpf ?? '').replace(/\D/g, '') === normalizedCpfQuery.value)
  }
  const q = searchQuery.value.toLowerCase().trim()
  return [...mockPacientes].filter(p => p.nome.toLowerCase().includes(q)).sort((a, b) => a.nome.localeCompare(b.nome))
})

watch(searchQuery, () => { currentPage.value = 1 })

const totalPages = computed(() => Math.max(1, Math.ceil(filteredPacientes.value.length / PAGE_SIZE)))

const paginatedPacientes = computed(() =>
  filteredPacientes.value.slice((currentPage.value - 1) * PAGE_SIZE, currentPage.value * PAGE_SIZE)
)

function getInitials(nome: string): string {
  return nome.split(' ').filter(Boolean).slice(0, 2).map(w => w[0].toUpperCase()).join('')
}


function toggleCpfReveal(id: string) {
  const next = new Set(revealedCpfs.value)
  if (next.has(id)) {
    next.delete(id)
  } else {
    next.add(id)
    setTimeout(() => {
      revealedCpfs.value = new Set([...revealedCpfs.value].filter(x => x !== id))
    }, 5000)
  }
  revealedCpfs.value = next
}

function getLastConsultation(paciente: Paciente): string {
  const primary = paciente.prontuarios?.find(p => p.numero === paciente.prontuarioPrimario) ?? paciente.prontuarios?.[0]
  return primary?.consultas?.[0]?.data ?? '—'
}

function handleRowClick(paciente: Paciente) {
  router.push(`/briefing?source=base&patientId=${paciente.id}`)
}
</script>

// mockup/app/pacientes/page.tsx
"use client"

import { useState, useMemo, useEffect } from "react"
import { useRouter } from "next/navigation"
import { MainLayout } from "@/components/main-layout"
import { Input } from "@/components/ui/input"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Empty } from "@/components/ui/empty"
import { Search, Eye, EyeOff, UserX, Users, ChevronLeft, ChevronRight } from "lucide-react"
import { allPatients } from "@/lib/mock-data"
import { cn, getInitials } from "@/lib/utils"

const PAGE_SIZE = 20

function maskCpf(cpf: string): string {
  // Mask: ***.xxx.xxx-** (reveal middle 6 digits: positions 4-9)
  return cpf.replace(/^(\d{3})\.(\d{3})\.(\d{3})-(\d{2})$/, "***.$2.$3-**")
}

export default function BasePacientes() {
  const router = useRouter()
  const [searchQuery, setSearchQuery] = useState("")
  const [revealedCpfs, setRevealedCpfs] = useState<Set<string>>(new Set())
  const [currentPage, setCurrentPage] = useState(1)

  // Detect search mode: CPF if contains numbers or CPF format chars
  const isCpfSearch = /[\d.-]/.test(searchQuery)
  const normalizedCpfQuery = searchQuery.replace(/\D/g, "")
  const isCpfComplete = normalizedCpfQuery.length === 11

  // Filter patients based on search
  const filteredPatients = useMemo(() => {
    if (!searchQuery.trim()) {
      return [...allPatients].sort((a, b) => a.name.localeCompare(b.name))
    }

    if (isCpfSearch) {
      // CPF search: only show results when complete
      if (!isCpfComplete) {
        return []
      }
      return allPatients.filter((p) => {
        const patientCpfNormalized = p.cpf?.replace(/\D/g, "") || ""
        return patientCpfNormalized === normalizedCpfQuery
      })
    } else {
      // Name search: filter as user types
      const query = searchQuery.toLowerCase().trim()
      return allPatients
        .filter((p) => p.name.toLowerCase().includes(query))
        .sort((a, b) => a.name.localeCompare(b.name))
    }
  }, [searchQuery, isCpfSearch, isCpfComplete, normalizedCpfQuery])

  // Reset to page 1 whenever the search query changes
  useEffect(() => {
    setCurrentPage(1)
  }, [searchQuery])

  // Pagination
  const totalPages = Math.max(1, Math.ceil(filteredPatients.length / PAGE_SIZE))
  const paginatedPatients = filteredPatients.slice(
    (currentPage - 1) * PAGE_SIZE,
    currentPage * PAGE_SIZE
  )

  // Toggle CPF reveal with auto-hide after 5 seconds
  const toggleCpfReveal = (patientId: string, e: React.MouseEvent) => {
    e.stopPropagation()
    setRevealedCpfs((prev) => {
      const next = new Set(prev)
      if (next.has(patientId)) {
        next.delete(patientId)
      } else {
        next.add(patientId)
        // Auto-hide after 5 seconds
        setTimeout(() => {
          setRevealedCpfs((current) => {
            const updated = new Set(current)
            updated.delete(patientId)
            return updated
          })
        }, 5000)
      }
      return next
    })
  }

  const handleRowClick = (patientId: string) => {
    router.push(`/pacientes/${patientId}`)
  }

  // Get last consultation date for a patient
  const getLastConsultation = (patientId: string) => {
    const patient = allPatients.find(p => p.id === patientId)
    if (!patient?.prontuarios?.length) return "—"
    // Get the first consultation from the primary record
    const primaryProntuario = patient.prontuarios.find(p => p.number === patient.primaryRecord) || patient.prontuarios[0]
    return primaryProntuario.consultations.length > 0 ? primaryProntuario.consultations[0].date : "—"
  }

  return (
    <MainLayout title="Base de Pacientes">
      <div className="space-y-6">
        {/* Stats */}
        <div className="flex items-center gap-2 text-sm text-muted-foreground">
          <Users className="h-4 w-4" />
          <span>{allPatients.length} pacientes cadastrados</span>
        </div>

        {/* Search */}
        <div className="relative max-w-md">
          <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
          <Input
            placeholder="Buscar por nome ou CPF..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="pl-9"
          />
        </div>

        {/* CPF search helper message */}
        {isCpfSearch && !isCpfComplete && searchQuery.length > 0 && (
          <div className="rounded-md border border-amber-200 bg-amber-50 px-4 py-2 text-sm text-amber-800">
            Digite o CPF completo para buscar (LGPD)
          </div>
        )}

        {/* Patient List */}
        {filteredPatients.length === 0 ? (
          <div className="flex flex-col items-center justify-center py-12">
            <Empty
              icon={UserX}
              title={isCpfSearch && !isCpfComplete ? "Digite o CPF completo" : "Nenhum paciente encontrado"}
              description={
                isCpfSearch && !isCpfComplete
                  ? "Por razoes de privacidade (LGPD), a busca por CPF requer o numero completo."
                  : "Tente ajustar os termos de busca."
              }
            />
          </div>
        ) : (
          <>
            <div className="overflow-x-auto rounded-lg border border-slate-200 shadow-sm">
            <Table>
              <TableHeader>
                <TableRow className="bg-slate-50">
                  <TableHead className="pl-4 w-[280px]">Paciente</TableHead>
                  <TableHead className="hidden sm:table-cell w-[100px]">Idade</TableHead>
                  <TableHead className="hidden md:table-cell w-[150px]">Prontuario</TableHead>
                  <TableHead className="hidden lg:table-cell w-[180px]">CPF</TableHead>
                  <TableHead className="hidden xl:table-cell w-[140px]">Ultima consulta</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {paginatedPatients.map((patient) => {
                  const isRevealed = revealedCpfs.has(patient.id)
                  const displayCpf = isRevealed ? patient.cpf : maskCpf(patient.cpf || "")

                  return (
                    <TableRow
                      key={patient.id}
                      onClick={() => handleRowClick(patient.id)}
                      className="cursor-pointer hover:bg-slate-50 h-14 transition-colors"
                    >
                      <TableCell className="pl-4 py-3">
                        <div className="flex items-center gap-3">
                          <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-teal-100 text-teal-700 text-sm font-semibold">
                            {getInitials(patient.name)}
                          </div>
                          <div className="min-w-0">
                            <p className="font-medium truncate">{patient.name}</p>
                            {/* Mobile: show extra info */}
                            <div className="flex flex-wrap gap-2 sm:hidden mt-0.5 text-xs text-muted-foreground">
                              <span>{patient.age}</span>
                              <span>{patient.record}</span>
                            </div>
                          </div>
                        </div>
                      </TableCell>
                      <TableCell className="hidden sm:table-cell text-sm">{patient.age}</TableCell>
                      <TableCell className="hidden md:table-cell text-sm text-muted-foreground">
                        {patient.record}
                      </TableCell>
                      <TableCell className="hidden lg:table-cell">
                        <div className="flex items-center gap-2">
                          <span className="text-sm font-mono text-muted-foreground">{displayCpf}</span>
                          <Button
                            variant="ghost"
                            size="sm"
                            className="h-7 w-7 p-0"
                            onClick={(e) => toggleCpfReveal(patient.id, e)}
                          >
                            {isRevealed ? (
                              <EyeOff className="h-3.5 w-3.5 text-muted-foreground" />
                            ) : (
                              <Eye className="h-3.5 w-3.5 text-muted-foreground" />
                            )}
                          </Button>
                        </div>
                      </TableCell>
                      <TableCell className="hidden xl:table-cell text-sm text-muted-foreground">
                        {getLastConsultation(patient.id)}
                      </TableCell>
                    </TableRow>
                  )
                })}
              </TableBody>
            </Table>
          </div>

          {/* Pagination */}
          {filteredPatients.length > PAGE_SIZE && (
            <div className="flex items-center justify-between pt-4 border-t border-slate-200">
              <p className="text-sm text-muted-foreground">
                Mostrando {((currentPage - 1) * PAGE_SIZE) + 1}–{Math.min(currentPage * PAGE_SIZE, filteredPatients.length)} de{" "}
                {filteredPatients.length} pacientes
              </p>
              <div className="flex items-center gap-2">
                <Button 
                  variant="outline" 
                  size="sm" 
                  disabled={currentPage === 1}
                  onClick={() => setCurrentPage(p => p - 1)}
                >
                  <ChevronLeft className="h-4 w-4 mr-1" />
                  Anterior
                </Button>
                <span className="text-sm font-medium px-2">
                  {currentPage} / {totalPages}
                </span>
                <Button 
                  variant="outline" 
                  size="sm" 
                  disabled={currentPage === totalPages}
                  onClick={() => setCurrentPage(p => p + 1)}
                >
                  Proxima
                  <ChevronRight className="h-4 w-4 ml-1" />
                </Button>
              </div>
            </div>
          )}
        </>
      )}
      </div>
    </MainLayout>
  )
}
